services:
  tests:
    network_mode: host

  test_framework:
    build: { context: ., dockerfile: backend/Dockerfile }
    environment:
      HOST_ARTIFACTS: $HOST_ARTIFACTS
    volumes:
      - ./:/app
      - $HOST_ARTIFACTS:$HOST_ARTIFACTS
    stop_signal: SIGINT
    stop_grace_period: 5s
