services:
  tests:
    image: test-pw-user-hub-web-app-tests
    build: { context: ., dockerfile: Dockerfile }
    working_dir: /tests
    environment:
      PYTHONPATH: /tests
      HOST_ARTIFACTS: $HOST_ARTIFACTS
      BASE_URL: "http://localhost:5173"
    volumes:
      - .:/tests
      - $HOST_ARTIFACTS:$HOST_ARTIFACTS
      - ./:/workspace/artifacts
    network_mode: host
    # command: bash -lc "pytest -q"
    command: bash -lc "xvfb-run -a -s '-screen 0 1920x1080x24' pytest -q tests"
