services:
  tests:
    build: { context: ., dockerfile: Dockerfile }
    environment:
      HOST_ARTIFACTS: $HOST_ARTIFACTS
      BASE_URL: "http://localhost:5173"
    volumes:
      - ./:/app
      - $HOST_ARTIFACTS:$HOST_ARTIFACTS
    network_mode: host
    command: bash -lc "pytest -q"
