base_url: ${BASE_URL}
api_url: ${API_URL}
headless: ${HEADLESS}
browsers: ${BROWSERS}
default_locale: ${DEFAULT_LOCALE}
slowmo_ms: 0
trace: "on-first-retry"
video: "retain-on-failure"
screenshot: "only-on-failure"
