version: 1

formatters:
  std:
    format: "%(asctime)s | %(levelname)s | %(name)s | %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: std
    level: INFO
  file:
    class: logging.FileHandler
    formatter: std
    filename: logs/test.log
    level: DEBUG

loggers:
  ui:
    level: DEBUG
    handlers: [console, file]
    propagate: no

root:
  level: INFO
  handlers: [console, file]
