name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - ".**"
      - ".github/workflows/docker-image.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - ".**"
      - ".github/workflows/docker-image.yml"
  workflow_dispatch:

jobs:
  test:
    name: Build backend image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: backend/Dockerfile
          push: false
          tags: ${{ github.repository }}-backend:ci,${{ github.repository }}-backend:sha-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
